name: OHMGPHOTO
favicon: null
layout_spectrum: 0.7954733669757843
typography_spectrum: 0.6596271407324821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.49812231305986643
  lightness: 0.10976476036012173
  saturation: 0.7188580723013729
  rhythmicContrast: 0.7011248744092882
purpose: []
