name: OHMGPHOTO
favicon: null
layout_spectrum: 0.20019
typography_spectrum: 0.27706
title: 'Oh! MG Photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d7dcd7'
    - '#a1a1a1'
    - '#595555'
    - '#797676'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
