name: OHMGPHOTO
favicon: null
layout_spectrum: 0.71687
typography_spectrum: 0.70413
title: Oh! MG Photo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4b8a8'
    - '#d2cfc9'
    - '#c6c6bc'
    - '#000000'
    - '#a2a2a2'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
