name: OHMGPHOTO
favicon: null
layout_spectrum: 0.7954733669757843
typography_spectrum: 0.6596271407324821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d92a9'
    - '#fdfff2'
    - '#184a7b'
    - '#2b2f25'
    - '#416b90'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.7011248744092882
purpose: []
